import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { NuqsAdapter } from 'nuqs/adapters/next/app';

import { Toaster } from '@/components/ui/sonner';
import { ThemeProvider } from '@/providers/theme.provider';
import { TanstackQueryProvider } from '@/providers/tanstack-query.provider';

import './globals.css';
import { Footer } from './_components/footer';

const interSans = Inter({
  variable: '--app-font',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Login',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: WithChildren) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body className={`${interSans.variable} antialiased`}>
        <NuqsAdapter>
          <TanstackQueryProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              disableTransitionOnChange
            >
              {children}
              <Toaster />
              <Footer />
            </ThemeProvider>
          </TanstackQueryProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
